### ISSUE TITLE
运行报错， list index out of range

### ISSUE THREAD

**Issue by lvlynn** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#21]
报错内容如下：
OpenAI version is compatible.
Traceback (most recent call last):
  File "c:\Users\xxx\Downloads\auto_job_find\write_response.py", line 183, in <module>
    vectorstore = get_vectorstore(chunks)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\xxx\Downloads\auto_job_find\langchain_functions.py", line 54, in get_vectorstore
    vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\miniconda3\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 914, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
  File "C:\Users\xxx\miniconda3\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 873, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
                                  ~~~~~~~~~~^^^
IndexError: list index out of range
这个 faiss依赖包应该安装哪个呢， 我安装的是faiss-cpu

**Comment by SDLi416** [comment]
> 报错内容如下： OpenAI version is compatible. Traceback (most recent call last): File "c:\Users\xxx\Downloads\auto_job_find\write_response.py", line 183, in vectorstore = get_vectorstore(chunks) ^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\xxx\Downloads\auto_job_find\langchain_functions.py", line 54, in get_vectorstore vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx\miniconda3\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 914, in from_texts return cls.__from( ^^^^^^^^^^^ File "C:\Users\xxx\miniconda3\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 873, in __from index = faiss.IndexFlatL2(len(embeddings[0])) ~~~~~~~~~~^^^ IndexError: list index out of range 这个 faiss依赖包应该安装哪个呢， 我安装的是faiss-cpu

我测试的时候用的是faiss-cpu，能提供更多的错误信息吗？看着应该是在简历向量化的时候出错了，方便的话能提供报错时候的简历就更好了

**Comment by john-dududu** [comment]
我也报一样的错误

**Comment by Frrrrrrrrank** [comment]
> 我这边测试用的是空白的pdf

测试如果用的空白pdf，感觉embedding的时候数据库会有些问题，比如都把空格算内容，可能导致out of list，你随便找一份文档试一下

**Comment by Ashley1014** [comment]
我用的是有内容的简历 也有list out of index的报错

**Comment by Zzmc1** [comment]
同样的报错，我曾一度以为是"get_text_chunks(text)"在使用"CharacterTextSplitter"来将输入的文本分割时文本没有包含分隔符，从而致使"split_text(text)"可能会返回一个空列表。
或者是"FAISS.from_texts(texts=text_chunks, embedding=embeddings)"在处理空的"text_chunks"时可能会抛出"IndexError: list index out of range"错误。
然后我就尝试调整”CharacterTextSplitter“的“chunk_size”或“chunk_overlap”参数，也尝试”textwrap“来重新分割文本，结果都失败了。所以这个 IndexError: list index out of range 的报错怎么解决😭
