### ISSUE TITLE
发送求职信息不全/乱码 

### ISSUE THREAD

**Issue by WINTERYARK** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#22]
![屏幕截图 2024-01-09 232903](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/102876303/da0fd657-a7d6-4e6e-a66b-9c26757995cb)

可以正常扫码登录boss直聘，如图所示在给hr发送的求职信息不全并且看起来似乎有些怪，在发送第二个求职信息的时候输出的是乱码，随后不再继续检索职位喝发送信息。

如下面的代码所示，之前遇到一个报错然后我把langchain_functions.py文件中的temperature从3改成了2，不知道对我上面的错误会不会有影响，希望得到解答，谢谢
llm = ChatOpenAI(temperature=2, openai_api_base=OPENAI_BASE_URL, openai_api_key=OPENAI_API_KEY)

并且好像没有创建asistant

**Comment by SDLi416** [comment]
> ![屏幕截图 2024-01-09 232903](https://private-user-images.githubusercontent.com/102876303/295254036-da0fd657-a7d6-4e6e-a66b-9c26757995cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE5MTcsIm5iZiI6MTcwNDg3MTYxNywicGF0aCI6Ii8xMDI4NzYzMDMvMjk1MjU0MDM2LWRhMGZkNjU3LWE3ZDYtNGU2ZS1hNjZiLTljMjY3NTc5OTVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzI4MTVhNTBkNTA3MDcxMjQ4MTA5Yjg1YTk3ZTUyYjM4NWY0MjE0ZGVmZDA3MzMwMjliNTNiZjg4NDdhMDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MU9SNTrkoyyH2JqXdOrVZEl3cU5q8LKwMROnpnJcZNo)
> 
> 可以正常扫码登录boss直聘，如图所示在给hr发送的求职信息不全并且看起来似乎有些怪，在发送第二个求职信息的时候输出的是乱码，随后不再继续检索职位喝发送信息。
> 
> 如下面的代码所示，之前遇到一个报错然后我把langchain_functions.py文件中的temperature从3改成了2，不知道对我上面的错误会不会有影响，希望得到解答，谢谢 llm = ChatOpenAI(temperature=2, openai_api_base=OPENAI_BASE_URL, openai_api_key=OPENAI_API_KEY)
> 
> 并且好像没有创建asistant

修改temperature不会有影响，从图里看好像第一次发送求职信的时候就出问题了？但是这输出的内容有点怪异。。原本的prompt应该不会输出这个才对
如果使用的自定义的base url的话是不会走assistant的，因为很多的代理api并不支持创建assistant，如果要使用assistant的话环境变量里不要填OPENAI_BASE_URL

**Comment by WINTERYARK** [comment]
> > ![屏幕截图 2024-01-09 232903](https://private-user-images.githubusercontent.com/102876303/295254036-da0fd657-a7d6-4e6e-a66b-9c26757995cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE5MTcsIm5iZiI6MTcwNDg3MTYxNywicGF0aCI6Ii8xMDI4NzYzMDMvMjk1MjU0MDM2LWRhMGZkNjU3LWE3ZDYtNGU2ZS1hNjZiLTljMjY3NTc5OTVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzI4MTVhNTBkNTA3MDcxMjQ4MTA5Yjg1YTk3ZTUyYjM4NWY0MjE0ZGVmZDA3MzMwMjliNTNiZjg4NDdhMDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MU9SNTrkoyyH2JqXdOrVZEl3cU5q8LKwMROnpnJcZNo)
> > 可以正常扫码登录boss直聘，如图所示在给hr发送的求职信息不全并且看起来似乎有些怪，在发送第二个求职信息的时候输出的是乱码，随后不再继续检索职位喝发送信息。
> > 如下面的代码所示，之前遇到一个报错然后我把langchain_functions.py文件中的temperature从3改成了2，不知道对我上面的错误会不会有影响，希望得到解答，谢谢 llm = ChatOpenAI(temperature=2, openai_api_base=OPENAI_BASE_URL, openai_api_key=OPENAI_API_KEY)
> > 并且好像没有创建asistant
> 
> 修改temperature不会有影响，从图里看好像第一次发送求职信的时候就出问题了？但是这输出的内容有点怪异。。原本的prompt应该不会输出这个才对 如果使用的自定义的base url的话是不会走assistant的，因为很多的代理api并不支持创建assistant，如果要使用assistant的话环境变量里不要填OPENAI_BASE_URL

输出的内容是很怪异，我用的是openai官方的api key，我只在. env文件中添加了api key，并没有填写OPENAI_BASE_URL。

之后我重新运行了程序，可以登陆上boss直聘但是并不能开始自动投递简历。并且输出乱码，如下图所示
![屏幕截图 2024-01-10 210351](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/102876303/fc9873a8-4859-4775-b4dd-901703fbb860)

**Comment by Frrrrrrrrank** [comment]
最后一张截图的错误应该是关闭了浏览器窗口？
如果是输出乱码的话，尝试一下把pdf转成txt，然后在代码的对应位置进行修改

**Comment by WINTERYARK** [comment]
我把我的pdf转换成了txt格式并且改动了下列代码：
file = client.files.create(file=open("my_cover.txt", "rb"),
                               purpose='assistants')

但是在运行后仍然报错：
OpenAI version is compatible.
Traceback (most recent call last):
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job__find__chatgpt__rpa-master\auto_job_find\write_response.py", line 183, in <module>
    vectorstore = get_vectorstore(chunks)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job__find__chatgpt__rpa-master\auto_job_find\langchain_functions.py", line 54, in get_vectorstore
    vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job__find__chatgpt__rpa-maste\venv\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 914, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
  File "D:\auto_job__find__chatgpt__rpa-master\auto_job__find__chatgpt__rpa-maste\venv\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 873, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
                                  ~~~~~~~~~~^^^
IndexError: list index out of range

尝试将文本缩短再试也是同样的报错

> 最后一张截图的错误应该是关闭了浏览器窗口？ 如果是输出乱码的话，尝试一下把pdf转成txt，然后在代码的对应位置进行修改

**Comment by Frrrrrrrrank** [comment]
这个问题我尝试复现，没成功...我给你挂了help wanted吧...看看有没有别的好兄弟能解决

你尝试一下用官方api，不用langchian，能成功吗？

**Comment by SDLi416** [comment]
前几天都没空看。。下午或者这两天我找时间排查一下吧

**Comment by WINTERYARK** [comment]
> 这个问题我尝试复现，没成功...我给你挂了help wanted吧...看看有没有别的好兄弟能解决
> 
> 你尝试一下用官方api，不用langchian，能成功吗？
我用的是官方的api，还是不太行。使用pdf版本可以登陆上boss直聘但是仍然报错。

**Comment by WINTERYARK** [comment]
> 这个问题我尝试复现，没成功...我给你挂了help wanted吧...看看有没有别的好兄弟能解决
> 
> 你尝试一下用官方api，不用langchian，能成功吗？

我使用的就是官方的api，好像还是不行，换成pdf上传后可以正常登录boss直聘但是仍然报错：

An error occurred: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF69DE32142+3514994]
	(No symbol) [0x00007FF69DA50CE2]
	(No symbol) [0x00007FF69D8F76AA]
	(No symbol) [0x00007FF69D941860]
	(No symbol) [0x00007FF69D94197C]
	(No symbol) [0x00007FF69D984EE7]
	(No symbol) [0x00007FF69D96602F]
	(No symbol) [0x00007FF69D9828F6]
	(No symbol) [0x00007FF69D965D93]
	(No symbol) [0x00007FF69D934BDC]
	(No symbol) [0x00007FF69D935C64]
	GetHandleVerifier [0x00007FF69DE5E16B+3695259]
	GetHandleVerifier [0x00007FF69DEB6737+4057191]
	GetHandleVerifier [0x00007FF69DEAE4E3+4023827]
	GetHandleVerifier [0x00007FF69DB804F9+689705]
	(No symbol) [0x00007FF69DA5C048]
	(No symbol) [0x00007FF69DA58044]
	(No symbol) [0x00007FF69DA581C9]
	(No symbol) [0x00007FF69DA488C4]
	BaseThreadInitThunk [0x00007FF9B8627614+20]
	RtlUserThreadStart [0x00007FF9B95A26F1+33]


进程已结束,退出代码0

**Comment by Frrrrrrrrank** [comment]
> > 这个问题我尝试复现，没成功...我给你挂了help wanted吧...看看有没有别的好兄弟能解决
> > 你尝试一下用官方api，不用langchian，能成功吗？
> 
> 我使用的就是官方的api，好像还是不行，换成pdf上传后可以正常登录boss直聘但是仍然报错：
> 
> An error occurred: Message: Stacktrace: GetHandleVerifier [0x00007FF69DE32142+3514994] (No symbol) [0x00007FF69DA50CE2] (No symbol) [0x00007FF69D8F76AA] (No symbol) [0x00007FF69D941860] (No symbol) [0x00007FF69D94197C] (No symbol) [0x00007FF69D984EE7] (No symbol) [0x00007FF69D96602F] (No symbol) [0x00007FF69D9828F6] (No symbol) [0x00007FF69D965D93] (No symbol) [0x00007FF69D934BDC] (No symbol) [0x00007FF69D935C64] GetHandleVerifier [0x00007FF69DE5E16B+3695259] GetHandleVerifier [0x00007FF69DEB6737+4057191] GetHandleVerifier [0x00007FF69DEAE4E3+4023827] GetHandleVerifier [0x00007FF69DB804F9+689705] (No symbol) [0x00007FF69DA5C048] (No symbol) [0x00007FF69DA58044] (No symbol) [0x00007FF69DA581C9] (No symbol) [0x00007FF69DA488C4] BaseThreadInitThunk [0x00007FF9B8627614+20] RtlUserThreadStart [0x00007FF9B95A26F1+33]
> 
> 进程已结束,退出代码0

这个是因为页面元素没有被抓取到，你能分享一下出错时候页面的截屏吗？以及您使用的浏览器

**Comment by Frrrrrrrrank** [comment]
关于第一个到了你的页面没有反应的问题，
在finding_jobs的def select_dropdown_option(driver, label):函数中，最新的应当如下：：
```
def select_dropdown_option(driver, label):
    # 尝试在具有特定类的元素中找到文本
    trigger_elements = driver.find_elements(By.XPATH, "//*[@class='recommend-job-btn has-tooltip']")

    # 标记是否找到元素
    found = False

    for element in trigger_elements:
        if label in element.text:
            # 确保元素可见并且可点击
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable(element))
            element.click()  # 点击找到的元素
            found = True
            break

    # 如果在按钮中找到了文本，就不再继续下面的操作
    if found:
        return

    # 如果在按钮中没有找到文本，执行原来的下拉列表操作
    trigger_selector = "//*[@id='wrap']/div[2]/div[1]/div/div[1]/div"
    WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, trigger_selector))
    ).click()  # 打开下拉菜单

    dropdown_selector = "ul.dropdown-expect-list"
    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, dropdown_selector))
    )

    option_selector = f"//li[contains(text(), '{label}')]"
    WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, option_selector))
    ).click()  # 选择下拉菜单中的选项
```
因为在最开始的代码中没有考虑有些账号的职位标签时并列出现的（即你的情况），这种就抓取不到元素会报错，你试一下这个部分更改后，后面的逻辑跑不跑的通，乱码这个是否依然出现

如果还出现的话，你可以检查一下你api对应的openai管理assistant的平台，尝试一下是否文件上传成功，或者把你本地的assistant.json删除后再重新生成个新的assistant，希望能解决你的问题

**Comment by WINTERYARK** [comment]
感谢您的更新，我今天更改了这个部分的函数，可以跑通但是还是乱码
![屏幕截图 2024-01-14 172027](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/102876303/4b8a705c-ef94-47c4-8c77-a8b333097f17)

我检查了openai管理的assistant平台发现assistant并未被创建成功，本地的assistant.json文件也未被创建
![屏幕截图 2024-01-14 172338](https://github.com/Frrrrrrrrank/auto_job__find__chatgpt__rpa/assets/102876303/2f96a49e-6487-41ac-a379-ffb1bbec735f)

**Comment by Frrrrrrrrank** [comment]
那这个太奇怪了，按照我的程序，如果没有设置assistant.json的话，会首先自动创建，否则的话后面的逻辑都跑不了的。你对functions.py做了一些更改吗？而且我看你的打印信息，只有“OpenAI version is compatible”，正常来讲后面还会需要打印“Created a new assistant and saved the ID.”或者“Loaded existing assistant ID.”，请确保functions.py与write_response在同一文件夹，并尝试在电脑上搜索assistant.json，如果对functions.py你做出了任何更改，请将更改放在这里。

另外，你的是mac系统吗？
