### ISSUE TITLE
OpenAI version is compatible报错

### ISSUE THREAD

**Issue by LTtt456c** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#46]
OpenAI version is compatible.
Traceback (most recent call last):
  File "D:\Code\python\auto_job__find__chatgpt__rpa\auto_job_find\write_response.py", line 188, in <module>
    vectorstore = get_vectorstore(chunks)
  File "D:\Code\python\auto_job__find__chatgpt__rpa\auto_job_find\langchain_functions.py", line 54, in get_vectorstore
    vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings)
  File "D:\Program Files\Python310\lib\site-packages\langchain_community\vectorstores\faiss.py", line 959, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "D:\Program Files\Python310\lib\site-packages\langchain_community\embeddings\openai.py", line 668, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "D:\Program Files\Python310\lib\site-packages\langchain_community\embeddings\openai.py", line 494, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "D:\Program Files\Python310\lib\site-packages\langchain_community\embeddings\openai.py", line 116, in embed_with_retry
    return embeddings.client.create(**kwargs)
  File "D:\Program Files\Python310\lib\site-packages\openai\resources\embeddings.py", line 106, in create
    return self._post(
  File "D:\Program Files\Python310\lib\site-packages\openai\_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\Program Files\Python310\lib\site-packages\openai\_base_client.py", line 853, in request
    return self._request(
  File "D:\Program Files\Python310\lib\site-packages\openai\_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by LTtt456c** [comment]
GPT的key是第三方的免费的，env地址设置的是 OPENAI_BASE_URL=https://api.chatanywhere.com.cn

**Comment by longsizhuo** [comment]
Related to the latest PR
