### ISSUE TITLE
为什么填了api还是会报错

### ISSUE THREAD

**Issue by 1916757740** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#55]
Traceback (most recent call last):
  File "D:\Resource\python\auto_job__find__chatgpt__rpa-master\auto_job_find\write_response.py", line 13, in <module>
    import functions
  File "D:\Resource\python\auto_job__find__chatgpt__rpa-master\auto_job_find\functions.py", line 12, in <module>
    client = OpenAI(api_key=OPENAI_API_KEY, base_url=OPENAI_BASE_URL)
  File "D:\Resource\python\auto_job__find__chatgpt__rpa-master\auto_job_find\.venv\lib\site-packages\openai\_client.py", line 92, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by longsizhuo** [comment]
If you put API key exactly in correct place, maybe this error casued by different AI version
